name: Merge PR and Trigger Pipeline
on:
  pull_request:
    types: [opened]

jobs:
  merge-then-trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Merge PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl \
          -XPUT \
          -H "Authorization: bearer $GITHUB_TOKEN" \
          -H 'Accept: application/vnd.github+json' \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
          -d '{"merge_method":"squash","head":"'"${{ github.head_ref }}"'","base":"'"${{ github.base_ref }}"'"}'

    - name: Trigger Pipeline
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl \
          -XPOST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/{WORKFLOW_NAME}/dispatches \
          --data '{"ref":"'"${{ github.ref }}"'","inputs":{}}'
